In [2]:
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from skimage.feature import hog
import tensorflow as tf
from tensorflow.keras import layers, models

In [3]:
from PIL import Image
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

# Include image processing functions

In [5]:
def image_pipeline_with_resize(folder_path,height,width):
    images_data = []
    labels = []
    size_=(width,height)
    Classes = os.listdir(folder_path)

    for i in range(len(Classes)):
        new_path = folder_path + '/' + Classes[i]
        Classes2 = os.listdir(new_path)

        for j in range(len(Classes2)):
            

            image_path = folder_path + '/' + Classes[i] + '/' + Classes2[j]
            
            try:
                # Attempt to open the image
                image = Image.open(image_path)

                # Resize the images
                img_resized = image.resize(size_, Image.Resampling.LANCZOS)
                
                # Convert the image to a NumPy array
                image_array = np.array(img_resized)
                
                # Append the image array to the list
                images_data.append(image_array)
                
                labels.append(Classes[i])
            
            except (IOError, OSError) as e:
                # Handle the exception (e.g., print a warning, skip the image, etc.)
                print(f"Error processing {image_path}: {e}")

    return images_data, labels

In [6]:
def RGB_to_grayscale(image_array):
    length= len(image_array)
    images_list=[]
    for i in range(length):
        # Compute the weighted sum to convert to grayscale
        images_list.append(np.dot(image_array[i], [0.299, 0.587, 0.114]))

    return images_list

In [7]:
def Image_scalling(data_list):
    list_length=len(data_list)
    new_data_list=[]
    for i in range(list_length):
        new_data_list.append((data_list[i]/255))

    return new_data_list

# Function to Change Labels

In [ ]:
import numpy as np

def convert_labels(labels):
    # Create a copy of the labels array to avoid modifying the original array
    labels=np.array(labels)
    converted_labels = labels.copy()
    
    # Convert 'cat' to 1 and 'dog' to 0
    converted_labels[labels == 'cat'] = 1
    converted_labels[labels == 'dog'] = 0
    
    return converted_labels  # Convert labels to integers


# Load the dataset

In [8]:
dataset_dir = 'dog_cat'
test_dir ='test_dog_cat'

In [9]:
xtrain,ytrain=image_pipeline_with_resize(dataset_dir,200,200)

In [10]:
xtest,ytest=image_pipeline_with_resize(test_dir,200,200)

# Create numpy 'npz' dataset

In [11]:
xtrain=np.array(xtrain)

In [12]:
ytrain=np.array(ytrain)

In [13]:
xtrain=np.array(xtest)

In [14]:
ytrain=np.array(ytest)

In [15]:
np.savez('dog_cat_dataset.npz',x_train=xtrain,y_train=ytrain,x_test=xtest,y_test=ytest)

# Load numpy 'npz' dataset

In [16]:
data = np.load('dog_cat_dataset.npz')

In [17]:
images11=data['x_test']

In [19]:
print(images11[0])

[[[ 59  81 104]
  [ 55  76 100]
  [ 54  73  97]
  ...
  [126 104  66]
  [126 104  65]
  [128 103  63]]

 [[ 61  83 106]
  [ 58  79 103]
  [ 56  75  99]
  ...
  [125 103  65]
  [124 102  62]
  [127 102  61]]

 [[ 57  79 102]
  [ 60  80 104]
  [ 59  79 103]
  ...
  [126 104  64]
  [126 103  62]
  [131 105  64]]

 ...

 [[ 78  70  62]
  [ 83  74  67]
  [ 82  72  65]
  ...
  [171 142 102]
  [164 136  96]
  [156 126  88]]

 [[ 81  73  65]
  [ 84  75  68]
  [ 84  74  67]
  ...
  [170 141 101]
  [169 139 100]
  [165 135  97]]

 [[ 78  70  63]
  [ 83  74  67]
  [ 85  75  69]
  ...
  [169 140 100]
  [168 138 100]
  [165 135  97]]]
